name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build (${{ matrix.os }}

    strategy:
      # let us get failures from other jobs even if one fails
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'

      - name: Install JUnit report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Install gocov
        run: go install github.com/axw/gocov/gocov@latest

      - name: Install gocov-xml
        run: go install github.com/AlekSi/gocov-xml@latest

      - name: Install gocov-html
        run: go install github.com/matm/gocov-html/cmd/gocov-html@latest

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: build windows amd64
        run: go build -o ./bin/adotest_windows_amd64.exe ./cmd
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: build windows arm64
        run: go build -o ./bin/adotest_windows_arm64.exe ./cmd
        env:
          GOOS: windows
          GOARCH: arm64
          CGO_ENABLED: 0

      - name: build linux amd64
        run: go build -o ./bin/adotest_linux_amd64 ./cmd
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: build linux arm64
        run: go build -o ./bin/adotest_linux_arm64 ./cmd
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0

      - name: run tests
        run: bash ./run_tests_with_coverage.sh

  staticchecks:
    name: Static Checks

    strategy:
      # let us get failures from other jobs even if one fails
      fail-fast: false

    # only run this on ubuntu since it is just inspecting the code and the commandline on windows gives errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: run gosec
        run: $(go env GOPATH)/bin/gosec ./...

      - name: run staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...



